# Generated by Django 3.2.3 on 2021-06-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='githuburl',
            field=models.URLField(null=True),
        ),
    ]
