# Generated by Django 3.2.3 on 2021-06-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_githuburl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='githuburl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
