# Generated by Django 3.2.3 on 2021-06-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210630_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.FloatField(),
        ),
    ]
