# Generated by Django 3.2.3 on 2021-06-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210630_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagealbum',
            name='name',
            field=models.CharField(default='Album', max_length=255),
        ),
    ]
