# Generated by Django 3.2.3 on 2021-06-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210630_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagealbum',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
