# Generated by Django 3.2.3 on 2021-07-05 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210705_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='importance',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
