# Generated by Django 3.2.3 on 2021-07-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_project_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gif',
            field=models.URLField(blank=True, null=True),
        ),
    ]
