# Generated by Django 3.2.3 on 2021-07-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_project_gif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='length',
            new_name='height',
        ),
    ]
