# Generated by Django 3.2.3 on 2021-07-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_project_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
